### ISSUE TITLE
空间问题

### ISSUE THREAD

**Issue by dslu7733** [vergil5750/HUST_OS_fs_experiment#1]
你好，我最近参考了你的项目，其中发现了一些问题，特此向你请教。
首先是HUST_inode结构体，你在博客里说它是256字节，但是编译器对于结构体有默认的字节对齐要求，所以实际为264字节。
`struct HUST_inode {
	mode_t mode;//sizeof(mode_t) is 4
	uint64_t inode_no;
	uint64_t blocks;	//block number
	uint64_t block[HUST_N_BLOCKS]; //HUST_N_BLOCKS = 10
	union {
		uint64_t file_size;
		uint64_t dir_children_count;
	};
    int32_t i_uid; 
    int32_t i_gid;
    int32_t i_nlink;
    
    int64_t i_atime;
    int64_t i_mtime;
    int64_t i_ctime;
    char padding[112];
};`

之后是“磁盘”（指回环设备）的空间划分，有以下代码
`disk_size = get_file_size(path);
...
super_block.blocks_count = disk_size/HUST_BLOCKSIZE;
...
super_block.inodes_count = super_block.blocks_count;`
貌似你想把磁盘的空间都分配给block，但是这样一来磁盘空间分配额度不就没有了吗？
据我了解inode也是需要磁盘空间的吧，这里是你有别的顾虑或原因吗，能否为我解答一下，谢谢。

**Comment by ZhangShurong** [comment]
第一个问题，应该是我算错了。
第二个问题，block和inode不冲突。inode也是存在block里面的。
不好意思，最近太忙了。。。。
